<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    protected $errors;

    public function save(array $options = [])
    {
        $this->beforeCreate();
        return parent::save($options); // TODO: Change the autogenerated stub
        $this->afterCreate();
    }

    public function update(array $attributes = [], array $options = [])
    {
        return parent::update($attributes, $options); // TODO: Change the autogenerated stub
    }

    public function beforeCreate()
    {
        $validator = \Validator::make($this->attributes, $this::$rules);

        if ($validator->fails()) {
            $this->errors = $validator->errors();
            return false;
        }

    }

    public function afterCreate()
    {

    }

}
